### ISSUE TITLE
Multiple Release EPIC: Upgrade clusterset API to v1beta2, use the "exclusiveClusterSetLabel" as default for clusterSetType, and deprecate the "legacyclusterset"

### ISSUE THREAD

**Issue by ldpliu** [open-cluster-management-io/ocm#67]
By introducing a new version of clusterset api (v1beta2), we can change the migration path as below.

Release 0.9.0

- [x] Add exclusiveClustersetLabel selector type in clusterset api v1beta1
- [x] [Add clusterset api v1beta2 to remove the support of legacyClustersetLabel selector type](https://github.com/open-cluster-management-io/api/pull/174)
- [x] Add conversion webhook to transform clusterset CRs between v1beta1 and v1beta2
- [x] Mark clusterset api v1beta1 as deprecated
- [x] [update documentation for v1beta2](https://github.com/open-cluster-management-io/OCM/issues/77)

Release 0.10.0
- [x] upgrade clusterset api to v1beta2 for each component
  - [x] https://github.com/open-cluster-management-io/OCM/issues/74
  - [x] https://github.com/open-cluster-management-io/OCM/issues/75
  - [x] https://github.com/open-cluster-management-io/OCM/issues/76

- [x] Other clusterset consumers (external consumers) must upgrade to clusterset api v1beta2

Release 0.11.0 
- [x] Migrate storage version of clusterset api to v1beta2

Release 0.12.0
- [ ] Remove clusterset api v1beta1

**Comment by elgnay** [comment]
Release N

[ ] Add exclusiveClustersetLabel selector type in clusterset api v1beta1
[ ] Add clusterset api v1beta2 to remove the support of legacyClustersetLabel selector type
[ ] Add conversion webhook to transform clusterset CRs between v1beta1 and v1beta2
[ ] Change internal consumers(ui/foundation/submarinar-addon/placement) to use clusterset api v1beta2
[ ] Other clusterset consumers (external consumers) can upgrade to clusterset api v1beta2

Release N+1

[ ] Mark clusterset api v1beta1 as deprecated
[ ] Migrate storage version of clusterset api to v1beta2
[ ] Other clusterset consumers (external consumers) must upgrade to clusterset api v1beta2

Release N+2

[ ] Remove clusterset api v1beta1

**Comment by haoqing0110** [comment]
Remove clusterset api v1beta1 PRs:
https://github.com/open-cluster-management-io/api/pull/266

**Comment by xuezhaojun** [comment]
Upgrade cluster-proxy clusterset v1beta1: https://github.com/open-cluster-management-io/cluster-proxy/pull/167
